version: '3.4'
services:
  prologic-api:
    container_name: prologic-webapi
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: prologic/webapi:${PROLOGIC_WEBAPI_TAG}
    ports:
      - '8000:8000'
    hostname: prologic-webapi
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - "prologic-db"
    stdin_open: true
    tty: true

  prologic-db:
    image: 'postgres:9.6.2'
    container_name: prologic-db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /tmp
    ports:
      - '5432:5432'
    hostname: postgres-log
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - './docker-volumes/postgres:/var/lib/postgresql/data'   


      
