version: '3.4'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: prologyc/server:latest
    ports:
      - '8433:8433'
    stdin_open: true
    tty: true
  postgres:
    image: postgres:9.6.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prologyc
